import { Providers } from "@/redux/provider";
import "./globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
    title: "SamNote",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Navigation>{children}</Navigation>
                </Providers>
            </body>
        </html>
    );
}
