import { Providers } from '@/redux/provider'
import './globals.css'
import type { Metadata } from 'next'



export const metadata: Metadata = {
  title: 'SamNote',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <Providers><h1>header</h1>{children}</Providers>
      </body>
    </html>
  )
}
